# app/.streamlit/app.yml

# Optional: Custom Streamlit Settings
# Streamlit Cloud will read this on deployment

[theme]
base = "light"
primaryColor = "#1F77B4"
secondaryBackgroundColor = "#F0F2F6"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
